import Head from "next/head";
import Image from "next/image";
import { Component, createRef, useCallback, useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { PlusIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import Feed from "../components/feed";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Feed />
    </div>
  );
}
